research_task:
  description: >
    Conduct a thorough research about {topic}, using mainly the resources given to you via the tools.
    Make sure you find any interesting and relevant information given
    the current year is 2025.
  expected_output: >
    A list with 10 bullet points of the most relevant information about {topic} in {language}
  agent: researcher

editor_task:
  description: >
    Plan and structure a blog article about {topic}.
    Make sure to cover the most important pieces of information.
    Word Count Target: {length}
    Information Depth: {information_level}
    Reader Skill Level: {language_level}
    Writing Style: {tone}
    Article Language: {language}
    Extra Notes: {additional_information}
    Context History: {history}
  expected_output: >
    A list of bullet points of the topic of each paragraph about {topic} in {language}
  agent: editor

writer_task:
  description: >
    Write a blog article about {topic} using the list of bullet points provided.
    Use the list of paragraph topics provided, and base each paragraph on the topic given.
    Word Count Target: {length}
    Information Depth: {information_level}
    Reader Skill Level: {language_level}
    Writing Style: {tone}
    Article Language: {language}
    Extra Notes: {additional_information}
    Context History: {history}
  expected_output: >
    A blog article about {topic} in {language}
  agent: writer

proofreader_task:
  description: >
    Proofread and factcheck the received blog article about {topic}.
    If a numerical fact is mentioned, check it with the tool.
    Word Count Target: {length}
    Information Depth: {information_level}
    Reader Skill Level: {language_level}
    Writing Style: {tone}
    Article Language: {language}
    Extra Notes: {additional_information}
    Context History: {history}
  expected_output: >
    The received blog article about {topic} in {language}
  agent: proofreader